# Generated by Django 4.2.7 on 2025-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_phone_alter_lead_created_at_alter_lead_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
