# Generated by Django 4.2.7 on 2025-05-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_property_company'),
        ('leads', '0003_alter_lead_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='LeadProperty',
        ),
        migrations.AlterModelOptions(
            name='leadproperty',
            options={'verbose_name': 'Lead de Propiedad', 'verbose_name_plural': 'Leads de Propiedades'},
        ),
        migrations.CreateModel(
            name='LeadCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.CharField(max_length=300, verbose_name='Mensaje')),
                ('done', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Lead de Empresa',
                'verbose_name_plural': 'Leads de Empresas',
            },
        ),
    ]
