# Generated by Django 4.2.7 on 2025-05-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_property_company'),
        ('leads', '0004_rename_lead_leadproperty_alter_leadproperty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.CharField(max_length=300, verbose_name='Mensaje')),
                ('done', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.company', verbose_name='Empresa')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Lead de Propiedad',
                'verbose_name_plural': 'Leads de Propiedades',
            },
        ),
        migrations.RemoveField(
            model_name='leadproperty',
            name='property',
        ),
        migrations.DeleteModel(
            name='LeadCompany',
        ),
        migrations.DeleteModel(
            name='LeadProperty',
        ),
    ]
