# Generated by Django 4.2.7 on 2025-05-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_remove_leadproperty_property_delete_leadcompany_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
