# Generated by Django 4.2.7 on 2026-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='property',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Propiedad'),
        ),
    ]
