# Generated by Django 4.2.7 on 2025-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clave')),
                ('es', models.TextField(help_text='Texto original en español', verbose_name='Español')),
                ('en', models.TextField(help_text='Texto traducido al inglés', verbose_name='Inglés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
            },
        ),
    ]
