# Generated by Django 4.2.7 on 2025-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_translationgroup_alter_translation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='en',
            field=models.CharField(help_text='Traducción al inglés', max_length=255, verbose_name='Inglés'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='es',
            field=models.CharField(help_text='Texto original en español', max_length=255, verbose_name='Español'),
        ),
    ]
