# Generated by Django 4.2.7 on 2025-06-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_image_options_post_banner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post', verbose_name='Entrada relacionada'),
        ),
    ]
