# Generated by Django 4.2.7 on 2025-07-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_related_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Itzimna Team', max_length=255, verbose_name='Autor'),
        ),
    ]
