# Generated by Django 4.2.7 on 2025-01-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la categoría', max_length=255, unique=True)),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales', null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la empresa', max_length=255, unique=True)),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo (opcional)', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la ubicación', max_length=255, unique=True)),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales', null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Nombre del vendedor', max_length=255)),
                ('last_name', models.CharField(help_text='Apellido del vendedor', max_length=255)),
                ('phone', models.CharField(help_text='Teléfono del vendedor', max_length=255, unique=True)),
                ('has_whatsapp', models.BooleanField(default=False, help_text='Tiene WhatsApp')),
                ('email', models.EmailField(help_text='Correo electrónico del vendedor', max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del desarrollo o propiedad', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio', max_digits=10)),
                ('meters', models.DecimalField(decimal_places=2, help_text='Metros cuadrados', max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Activo')),
                ('description', models.TextField(help_text='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización')),
                ('category', models.ForeignKey(help_text='Categoría', on_delete=django.db.models.deletion.CASCADE, to='properties.category')),
                ('company', models.ForeignKey(help_text='Empresa', on_delete=django.db.models.deletion.CASCADE, to='properties.company')),
                ('seller', models.ForeignKey(help_text='Vendedor', on_delete=django.db.models.deletion.CASCADE, to='properties.seller')),
            ],
        ),
    ]
