# Generated by Django 4.2.7 on 2025-01-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='company',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo (opcional)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='location',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de la ubicación'),
        ),
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='property',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='property',
            name='meters',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Metros cuadrados'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del desarrollo o propiedad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.seller', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico del vendedor'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del vendedor'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='has_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Tiene WhatsApp'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellido del vendedor'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Teléfono del vendedor'),
        ),
    ]
