# Generated by Django 4.2.7 on 2025-01-14 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_category_details_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.location', verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
