# Generated by Django 4.2.7 on 2025-01-14 22:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
