# Generated by Django 4.2.7 on 2025-01-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_options_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
