# Generated by Django 4.2.7 on 2025-01-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_active_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'Imagen de propiedad', 'verbose_name_plural': 'Imágenes de propiedades'},
        ),
    ]
