# Generated by Django 4.2.7 on 2025-01-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertyimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
    ]
