# Generated by Django 4.2.7 on 2025-01-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_translationgroup_alter_translation_created_at_and_more'),
        ('properties', '0008_alter_propertyimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.translation', verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.translation', verbose_name='Nombre de la ubicación'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.translation', verbose_name='Descripción'),
        ),
    ]
