# Generated by Django 4.2.7 on 2025-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_category_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(default=None, verbose_name='Descripción en inglés'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='description_es',
            field=models.TextField(default=None, verbose_name='Descripción en español'),
            preserve_default=False,
        ),
    ]
