# Generated by Django 4.2.7 on 2025-01-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('properties', '0012_alter_category_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.OneToOneField(default=1, help_text='Descripción que se mostrará en la lista de propiedades', on_delete=django.db.models.deletion.CASCADE, to='translations.translation', verbose_name='Descripción corta'),
            preserve_default=False,
        ),
    ]
