# Generated by Django 4.2.7 on 2025-01-30 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clave')),
                ('es', models.CharField(max_length=255, verbose_name='Descripción en español')),
                ('en', models.CharField(max_length=255, verbose_name='Descripción en inglés')),
            ],
            options={
                'verbose_name': 'Descripción corta',
                'verbose_name_plural': 'Descripciones cortas',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.OneToOneField(help_text='Descripción corta de la propiedad o desarrollo', on_delete=django.db.models.deletion.CASCADE, to='properties.shortdescription', verbose_name='Descripción corta'),
        ),
    ]
