# Generated by Django 4.2.7 on 2025-01-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_shortdescription_alter_property_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortdescription',
            old_name='key',
            new_name='name',
        ),
    ]
