# Generated by Django 4.2.7 on 2025-01-30 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('properties', '0016_remove_shortdescription_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdescription',
            name='name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='translations.translation', verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
