# Generated by Django 4.2.7 on 2025-01-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('properties', '0017_shortdescription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortdescription',
            name='name',
        ),
        migrations.AddField(
            model_name='shortdescription',
            name='description',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='translations.translation', verbose_name='Descripción corta'),
            preserve_default=False,
        ),
    ]
