# Generated by Django 4.2.7 on 2025-02-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_remove_shortdescription_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, help_text='Indica si se mostrará en la sección de destacados', verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, help_text='Indica si se mostrará en la página', verbose_name='Activo'),
        ),
    ]
