# Generated by Django 4.2.7 on 2025-04-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('properties', '0022_property_google_maps_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='translations.translation', verbose_name='Nombre de la categoría')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.tag', verbose_name='Etiquetas'),
        ),
    ]
