# Generated by Django 4.2.7 on 2025-05-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_alter_seller_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='details',
        ),
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='company-banners/', verbose_name='Banner de la empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles en inglés'),
        ),
        migrations.AddField(
            model_name='company',
            name='details_es',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles en español'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico de la empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_maps_src',
            field=models.TextField(blank=True, help_text='Puedes insertar el iframe completo', null=True, verbose_name='src de Google Maps'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.location', verbose_name='Ubicación de la empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono de la empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Indica si se mostrará la información de contacto de la empresa', verbose_name='Mostrar información de contacto'),
        ),
        migrations.AddField(
            model_name='company',
            name='social_media',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Rede sociale de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to='company-photos/', verbose_name='Logo de la empresa'),
            preserve_default=False,
        ),
    ]
