# Generated by Django 4.2.7 on 2025-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('House', 'Casa'), ('Townhouse', 'Casa adosada'), ('Condominium', 'Condominio'), ('Apartment', 'Departamento'), ('Duplex / Triplex / Fourplex', 'Dúplex / Tríplex / Cuádruplex'), ('Villa', 'Villa'), ('Penthouse', 'Penthouse'), ('Studio', 'Estudio'), ('Loft', 'Loft'), ('Mobile / Manufactured Home', 'Casa móvil / prefabricada'), ('Tiny Home', 'Mini casa'), ('Cottage / Cabin', 'Cabaña'), ('Office Space', 'Oficina'), ('Retail Storefront / Shop', 'Tienda / Local comercial'), ('Shopping Center / Mall Unit', 'Local en centro comercial'), ('Warehouse', 'Bodega / Almacén'), ('Industrial Building', 'Nave industrial'), ('Hotel / Motel', 'Hotel / Motel'), ('Restaurant / Bar', 'Restaurante / Bar'), ('Coworking Space', 'Espacio de coworking'), ('Residential Lot', 'Terreno residencial'), ('Commercial Lot', 'Terreno comercial'), ('Agricultural Land', 'Terreno agrícola'), ('Industrial Land', 'Terreno industrial'), ('Ranch / Farm', 'Rancho / Granja'), ('Forest / Timberland', 'Bosque / Terreno forestal'), ('Mixed-Use Property', 'Propiedad de uso mixto'), ('Luxury Estate', 'Residencia de lujo'), ('Beachfront Property', 'Propiedad frente a la playa'), ('Golf Course Property', 'Propiedad en campo de golf'), ('Mountain Cabin', 'Cabaña en la montaña'), ('Historic Building', 'Edificio histórico'), ('Vacation Home / Resort Property', 'Casa de vacaciones / Propiedad turística')], default='House', help_text='Selecciona el tipo de propiedad que ofrece la empresa', max_length=50, verbose_name='Tipo de propiedad'),
        ),
    ]
