# Generated by Django 4.2.7 on 2025-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='details_en',
        ),
        migrations.RemoveField(
            model_name='company',
            name='details_es',
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción en inglés'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción en español'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('house', 'Casa'), ('townhouse', 'Casa adosada'), ('condo', 'Condominio'), ('apartment', 'Departamento'), ('duplex', 'Dúplex / Tríplex / Cuádruplex'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('studio', 'Estudio'), ('loft', 'Loft'), ('mobile_home', 'Casa móvil / prefabricada'), ('tiny_home', 'Mini casa'), ('cabin', 'Cabaña'), ('office', 'Oficina'), ('retail', 'Tienda / Local comercial'), ('mall_unit', 'Local en centro comercial'), ('warehouse', 'Bodega / Almacén'), ('industrial', 'Nave industrial'), ('hotel', 'Hotel / Motel'), ('restaurant', 'Restaurante / Bar'), ('coworking', 'Espacio de coworking'), ('residential_lot', 'Terreno residencial'), ('commercial_lot', 'Terreno comercial'), ('agricultural', 'Terreno agrícola'), ('industrial_land', 'Terreno industrial'), ('ranch', 'Rancho / Granja'), ('forest', 'Bosque / Terreno forestal'), ('mixed_use', 'Propiedad de uso mixto'), ('luxury', 'Residencia de lujo'), ('beachfront', 'Propiedad frente a la playa'), ('golf', 'Propiedad en campo de golf'), ('mountain', 'Cabaña en la montaña'), ('historic', 'Edificio histórico'), ('vacation', 'Casa de vacaciones / Propiedad turística')], default='House', help_text='Selecciona el tipo de propiedad que ofrece la empresa', max_length=50, verbose_name='Tipo de propiedad'),
        ),
    ]
