# Generated by Django 4.2.7 on 2025-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_remove_company_details_en_remove_company_details_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Descripción en inglés'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description_es',
            field=models.TextField(blank=True, default='', verbose_name='Descripción en español'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Correo electrónico de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='google_maps_src',
            field=models.TextField(blank=True, default='', help_text='Puedes insertar el iframe completo', verbose_name='src de Google Maps'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Teléfono de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='show_contact_info',
            field=models.BooleanField(default=False, help_text='Indica si se mostrará la información de contacto de la empresa', verbose_name='Mostrar información de contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='social_media',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Rede sociale de la empresa'),
        ),
    ]
