# Generated by Django 4.2.7 on 2025-05-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_alter_company_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Correo electrónico de la empresa'),
        ),
    ]
