# Generated by Django 4.2.7 on 2025-05-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_alter_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description_es',
        ),
        migrations.AddField(
            model_name='company',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles en inglés'),
        ),
        migrations.AddField(
            model_name='company',
            name='details_es',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles en español'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='google_maps_src',
            field=models.TextField(blank=True, help_text='Puedes insertar el iframe completo', null=True, verbose_name='src de Google Maps'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Indica si se mostrará la información de contacto de la empresa', verbose_name='Mostrar información de contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='social_media',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Rede sociale de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('House', 'Casa'), ('Townhouse', 'Casa adosada'), ('Condominium', 'Condominio'), ('Apartment', 'Departamento'), ('Duplex / Triplex / Fourplex', 'Dúplex / Tríplex / Cuádruplex'), ('Villa', 'Villa'), ('Penthouse', 'Penthouse'), ('Studio', 'Estudio'), ('Loft', 'Loft'), ('Mobile / Manufactured Home', 'Casa móvil / prefabricada'), ('Tiny Home', 'Mini casa'), ('Cottage / Cabin', 'Cabaña'), ('Office Space', 'Oficina'), ('Retail Storefront / Shop', 'Tienda / Local comercial'), ('Shopping Center / Mall Unit', 'Local en centro comercial'), ('Warehouse', 'Bodega / Almacén'), ('Industrial Building', 'Nave industrial'), ('Hotel / Motel', 'Hotel / Motel'), ('Restaurant / Bar', 'Restaurante / Bar'), ('Coworking Space', 'Espacio de coworking'), ('Residential Lot', 'Terreno residencial'), ('Commercial Lot', 'Terreno comercial'), ('Agricultural Land', 'Terreno agrícola'), ('Industrial Land', 'Terreno industrial'), ('Ranch / Farm', 'Rancho / Granja'), ('Forest / Timberland', 'Bosque / Terreno forestal'), ('Mixed-Use Property', 'Propiedad de uso mixto'), ('Luxury Estate', 'Residencia de lujo'), ('Beachfront Property', 'Propiedad frente a la playa'), ('Golf Course Property', 'Propiedad en campo de golf'), ('Mountain Cabin', 'Cabaña en la montaña'), ('Historic Building', 'Edificio histórico'), ('Vacation Home / Resort Property', 'Casa de vacaciones / Propiedad turística')], default='House', help_text='Selecciona el tipo de propiedad que ofrece la empresa', max_length=50, verbose_name='Tipo de propiedad'),
        ),
    ]
