# Generated by Django 4.2.7 on 2025-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_remove_company_details_en_remove_company_details_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='show_contact_info',
            field=models.BooleanField(default=False, help_text='Indica si se mostrará la información de contacto de la empresa', verbose_name='Mostrar información de contacto'),
        ),
    ]
