# Generated by Django 4.2.7 on 2025-05-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_alter_company_show_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_properties', to='properties.company', verbose_name='Empresa'),
        ),
    ]
