# Generated by Django 4.2.7 on 2025-05-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_property_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='promo_active',
            field=models.BooleanField(default=False, help_text='Indica si la empresa tiene una promoción activa', verbose_name='Promoción activa'),
        ),
    ]
