# Generated by Django 4.2.7 on 2025-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='review_name',
            field=models.CharField(blank=True, help_text='Nombre de la persona que hizo el review. Ejemplo: Juan Perez', max_length=255, null=True, verbose_name='Nombre de review'),
        ),
        migrations.AddField(
            model_name='property',
            name='review_rating',
            field=models.FloatField(blank=True, help_text='Rating que la persona le dio a la propiedad. Ejemplo: 4.5', null=True, verbose_name='Rating de review'),
        ),
    ]
