# Generated by Django 4.2.7 on 2025-07-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_property_review_name_property_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='review_count',
            field=models.IntegerField(blank=True, help_text='Cantidad de reviews que tiene en la propiedad. Ejemplo: 10', null=True, verbose_name='Cantidad de reviews'),
        ),
    ]
