# Generated by Django 4.2.7 on 2025-01-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del grupo')),
            ],
            options={
                'verbose_name': 'Grupo de traducción',
                'verbose_name_plural': 'Grupos de traducción',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clave')),
                ('es', models.CharField(help_text='Texto original en español', max_length=255, verbose_name='Español')),
                ('en', models.CharField(help_text='Traducción al inglés', max_length=255, verbose_name='Inglés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.translationgroup', verbose_name='Grupo de traducción')),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
            },
        ),
    ]
