# Generated by Django 4.2.7 on 2025-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestDevelopmentsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='best_developments_gallery_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Imagen de Mejores Desarrollos',
                'verbose_name_plural': 'Imágenes de Mejores Desarrollos',
            },
        ),
    ]
