# Generated by Django 4.2.7 on 2025-05-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestdevelopmentsimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='bestdevelopmentsimage',
            name='alt_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_developments_image_alt_text', to='translations.translation', verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='bestdevelopmentsimage',
            name='image',
            field=models.ImageField(upload_to='best_developments_gallery_images/', verbose_name='Imagen'),
        ),
    ]
