# Generated by Django 4.2.7 on 2025-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_bestdevelopmentsimage_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(upload_to='search_links_images/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('url', models.URLField(help_text='Url completa (https://www.google.com)', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Enlace de Búsqueda',
                'verbose_name_plural': 'Enlaces de Búsqueda',
            },
        ),
    ]
