# Generated by Django 4.2.7 on 2025-07-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('content', '0003_searchlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlinks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='searchlinks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='searchlinks',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_links_description', to='translations.translation', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='searchlinks',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_links_title', to='translations.translation', verbose_name='Título'),
        ),
    ]
