# Generated by Django 4.2.7 on 2025-07-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_searchlinks_created_at_searchlinks_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlinks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='searchlinks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
