# Generated by Django 4.2.7 on 2025-07-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('content', '0005_alter_searchlinks_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlinks',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_links_title', to='translations.translation', unique=True, verbose_name='Título'),
        ),
    ]
