# Generated by Django 4.2.7 on 2025-07-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('content', '0007_alter_searchlinks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlinks',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_links_title', to='translations.translation', verbose_name='Título'),
        ),
    ]
