# Generated by Django 4.2.7 on 2025-07-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('content', '0008_alter_searchlinks_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchLinks',
            new_name='SearchLink',
        ),
    ]
